<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy - EcoTrack</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <link href="{{ asset('css/legal-documents.css') }}" rel="stylesheet">
</head>
<body class="legal-document-page">
    <!-- Back Button -->
    <div class="back-button">
        <a href="{{ url('/') }}" class="back-link">
            <svg class="back-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
            </svg>
            Back to Home
        </a>
    </div>

    <div class="container">
        <h1>EcoTrack Privacy Policy</h1>
        <p>Last updated: {{ now()->format("F j, Y") }}</p>

        <div class="legal-notice">
            <p>EcoTrack and its affiliates ("Ecotrack", "we", "our", or "us") are committed to protecting your privacy. This privacy policy describes how we collect, use, disclose, and safeguard your information when you interact with EcoTrack through our websites, or web, and services, as well as during any direct communications with us (collectively, the "Services").</p>
            <p>This privacy policy applies specifically to platforms operated and maintained by EcoTrack Solutions Inc. that link to this statement. Please be aware that when you follow a link from our Services to an external site, that third party may have its own privacy policy, and EcoTrack is not responsible for the privacy practices of such websites. We encourage you to review the privacy policies of any third-party sites you visit.</p>
            <p>In addition to this privacy policy, we strongly recommend reviewing our Terms and Conditions which govern your use of our Services. By accessing or using any part of the Services, you agree to both the Terms and Conditions and the collection, use, and disclosure of your information as described in this privacy policy. If you do not agree with our practices, please do not use the Services.</p>
        </div>

        <div class="section-content">
            <h2>1. Information We Collect</h2>
            <div class="subsection">
                <p>We collect both personal and non-personal information to effectively deliver our services. Personal data includes your full name, residential address, barangay, contact number (used for SMS notifications), and optionally, your email address. These details are essential to ensure timely and accurate delivery of collection reminders. Non-personal data, such as system usage logs, user preferences, and timestamps of access, are also gathered to help us monitor performance and optimize our services. This data allows us to analyze patterns in system use and improve the overall experience.</p>
            </div>

            <h2>2. How We Use Your Information</h2>
            <div class="subsection">
                <p>Data is primarily collected through direct user input, such as when residents register via forms at the Environmental and Natural Resources Office (ENRO) or barangay offices. Additionally, data is collected through automated means, including logs generated by the system when SMS messages are sent or fail to deliver. In cases where address validation is necessary, we may access government-supplied records, provided proper authorization is granted. For minors under the age of 18, parental or guardian consent is required prior to data collection. Should any parent suspect their child has submitted information without consent, they may contact our office to request data deletion or account termination.</p>
            </div>

            <h2>3. Purpose of Data Collection</h2>
            <div class="subsection">
                <p>The information we collect serves multiple purposes. Primarily, it is used to send timely SMS reminders about garbage collection schedules, ensuring residents are informed and prepared. Additionally, collected data helps us manage and enhance the efficiency of garbage collection routes. This system also plays a crucial role in improving the overall effectiveness of local government services and ensuring compliance with waste management policies. By analyzing the data, we can assess community participation and optimize our processes to better serve the public.</p>
            </div>

            <h2>4. How We Use Your Data</h2>
            <div class="subsection">
                <p>Your data is used to personalize communication, such as sending SMS notifications for scheduled pickups or service updates. We also track pickup compliance and resident participation, which enables us to plan efficient routes and generate reports for the local authorities. These reports aid in informed decision-making, helping the LGU and ENRO to continually improve waste management strategies. All usage is aligned with our goal of delivering a cleaner and more responsive service to the public.</p>
            </div>

            <h2>5. Data Sharing and Disclosure</h2>
            <div class="subsection">
                <p>We respect your privacy and do not sell or commercialize your data. Information is only shared with authorized personnel, such as employees of the LGU or ENRO who need it to perform their duties. It may also be accessed by technical staff responsible for maintaining or upgrading the system. In rare instances, data may be disclosed to legal authorities if required by law. For minors, additional privacy measures are enforced, and consent can be revoked at any time by a parent or guardian.</p>
            </div>

            <h2>6. Data Retention</h2>
            <div class="subsection">
                <p>We retain your data only for as long as necessary to fulfill the system's operational, legal, or service improvement purposes. Once the data is no longer required, it is either anonymized or securely deleted in compliance with our data retention policies. For minors, data is stored only with verified parental consent and can be deleted upon formal request by the parent or guardian.</p>
            </div>

            <h2>7. Your Data Rights</h2>
            <div class="subsection">
                <p>As a user, you have the right to access your personal information and request corrections or updates. You may also request the deletion of your data or withdraw consent for its use at any time. Additionally, you have the right to file complaints regarding your data privacy with the National Privacy Commission. For accounts held by minors, these rights may be exercised by a parent or legal guardian.</p>
            </div>

            <h2>8. Data Security Measures</h2>
            <div class="subsection">
                <p>We take data security seriously and implement comprehensive measures to safeguard your information. All data is stored in encrypted databases with access restricted to authorized personnel through password-protected logins. Our systems undergo regular audits and backups to prevent data loss. SMS communications are sent through secure gateways, and firewall and anti-malware protections are in place to defend against unauthorized access or breaches.</p>
            </div>

            <h2>9. Policy Updates and Notification</h2>
            <div class="subsection">
                <p>We may revise this privacy policy to reflect changes in the law or our practices. When changes are made, residents will be notified through official barangay announcements, ENRO bulletin boards, or via SMS (when applicable). We encourage users to regularly review the policy to stay informed about how their data is handled.</p>
            </div>

            <h2>10. Contact Information</h2>
            <div class="subsection">
                <p>If you have any questions, concerns, or requests related to your personal data, you may contact our designated Data Protection Officer (DPO) at the Environmental and Natural Resources Office (ENRO).</p>
                <p>
                    <strong>Address:</strong> Environmental and Natural Resources Office (ENRO)<br>
                    Ormoc City Hall<br>
                    <strong>Phone:</strong> (123) 456-7890<br>
                    <strong>Email:</strong> privacy@enro-ormoc.gov.ph
                </p>
            </div>

            <h2>11. Legal Compliance</h2>
            <div class="subsection">
                <p>Our system complies fully with the Data Privacy Act of 2012 (Republic Act 10173) and other relevant local ordinances concerning data protection and digital privacy. While we do not currently operate outside the Philippines, we align with international best practices such as those outlined in the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), and the Children's Online Privacy Protection Act (COPPA), especially in handling data involving minors.</p>
            </div>

            <div class="legal-notice">
                <p><strong>Effective Date:</strong> {{ now()->format("F j, Y") }}</p>
                <p><strong>Last Updated:</strong> {{ now()->format("F j, Y") }}</p>
            </div>
        </div>
    </div>
</body>
</html> 